version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
    volumes:
      - /tmp/fitcado/postgres:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "5000:8080"
    volumes:
      - /tmp/images/:/images
